# Generated by Django 5.0.3 on 2025-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
