# Generated by Django 5.0.3 on 2025-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
