# Generated by Django 5.0.3 on 2025-02-02 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(verbose_name="วันที่จอง"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(verbose_name="เวลาสิ้นสุด"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(verbose_name="เวลาเริ่มต้น"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ราคารวม"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="สนามที่จอง",
            ),
        ),
    ]
