# Generated by Django 5.0.3 on 2025-02-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_booking_date_alter_booking_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
    ]
