# Generated by Django 5.0.3 on 2025-02-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_booking_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
    ]
