# Generated by Django 5.0.3 on 2025-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_booking_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user,admin",
                max_length=5,
            ),
        ),
    ]
