# Generated by Django 5.0.3 on 2025-02-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_remove_booking_payment_status_payment_receipt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
