# Generated by Django 5.0.3 on 2025-02-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_payment_payment_date_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_payment",
                to="booking.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_info",
                to="booking.booking",
            ),
        ),
    ]
