# Generated by Django 5.0.3 on 2025-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_booking_payment_alter_payment_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "เงินสด"),
                    ("credit_card", "บัตรเครดิต"),
                    ("bank_transfer", "โอนผ่านธนาคาร"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอดำเนินการ"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ถูกปฏิเสธ"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
