# Generated by Django 5.1.4 on 2025-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_payment_amount_alter_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=10,
            ),
        ),
    ]
