# Generated by Django 5.2.3 on 2025-08-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_remove_customuser_phone_number_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="nickname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
