# Generated by Django 5.2.3 on 2025-08-08 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_booking_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
