# Generated by Django 5.0.3 on 2025-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="field_images/"),
        ),
    ]
