# Generated by Django 5.0.3 on 2025-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_field_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("hourly", "รายชั่วโมง"),
                    ("half_day", "ครึ่งวัน"),
                    ("full_day", "เต็มวัน"),
                ],
                default="hourly",
                max_length=10,
            ),
        ),
    ]
