# Generated by Django 5.0.3 on 2025-01-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_booking_booking_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_type",
        ),
    ]
