# Generated by Django 5.0.3 on 2025-01-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_user_alter_booking_user_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="field",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="field",
        ),
    ]
