# Generated by Django 5.0.3 on 2025-01-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_remove_booking_field_remove_booking_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.field",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.booking",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="field",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.field",
            ),
            preserve_default=False,
        ),
    ]
